### ISSUE TITLE
It tests my proxies then kills itself

### ISSUE THREAD

**Issue by JimmyLongJohns** [WieszakWare/Hackord#7]
Ran it in a cmd and this is everything that was on there I can also attach put logs if you want just lmk
___________________________________________________________________________________________________________

13:15:03 ] [ INFO ] > Reading proxies from file: [ data/proxies.txt ]
[ 13:15:03 ] [ DEBUG ] > Checking Proxy: [ {'all://': 'http://38.94.109.12:80'} ]
[ 13:15:03 ] [ WARNING ] > Max proxy timeout set to [ 10 ]
Traceback (most recent call last):
  File "httpx\_transports\default.py", line 60, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 218, in handle_request
  File "httpcore\_sync\connection_pool.py", line 253, in handle_request
  File "httpcore\_sync\connection_pool.py", line 237, in handle_request
  File "httpcore\_sync\http_proxy.py", line 258, in handle_request
  File "httpcore\_sync\connection.py", line 90, in handle_request
  File "httpcore\_sync\http11.py", line 105, in handle_request
  File "httpcore\_sync\http11.py", line 84, in handle_request
  File "httpcore\_sync\http11.py", line 148, in _receive_response_headers
  File "httpcore\_sync\http11.py", line 191, in _receive_event
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "HackordV2.py", line 301, in <module>
  File "HackordV2.py", line 214, in run
  File "mod\discordapi.py", line 542, in Register
  File "mod\discordapi.py", line 138, in proxy_isworking
  File "httpx\_api.py", line 189, in get
  File "httpx\_api.py", line 100, in request
  File "httpx\_client.py", line 815, in request
  File "httpx\_client.py", line 902, in send
  File "httpx\_client.py", line 930, in _send_handling_auth
  File "httpx\_client.py", line 967, in _send_handling_redirects
  File "httpx\_client.py", line 1003, in _send_single_request
  File "httpx\_transports\default.py", line 217, in handle_request
  File "contextlib.py", line 153, in __exit__
  File "httpx\_transports\default.py", line 77, in map_httpcore_exceptions
httpx.RemoteProtocolError: Server disconnected without sending a response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HackordV2.py", line 305, in <module>
Exception
[15236] Failed to execute script 'HackordV2' due to unhandled exception!

C:\Users\jimmy\Desktop\disacct gen>

**Comment by WieszakWare** [comment]
### 1. Check your proxy format
Allowed proxy formats:
`host:port` [ example: `87.0.2.4:80`  ]
**OR**
`username:password@host:port` [ Example: [ usrhdfg:plahdhh@36.6.2.0:80 ] ]
### 2. Protocol Error
**What proxy type you are using?**
Default proxy type in Hackord is HTTP/HTTPS
If you want to use socks4 proxies or socks5 proxies you need to open config,json which is located in data folder.
Go to proxy section and replace http value with your proxy type.
![image](https://user-images.githubusercontent.com/111588764/201491181-1d75e727-6676-4553-b406-616eee427e00.png)
![image](https://user-images.githubusercontent.com/111588764/201491189-cbb99ed2-4177-4354-ab23-cda904d14d9e.png)
![image](https://user-images.githubusercontent.com/111588764/201491200-13f73049-88fb-444f-ba1c-b6796d2818de.png)

If you have any questios please reply to this comment!
Also i can help you on my [discord server](https://discord.gg/KCqrbVgSBF):

**Comment by WieszakWare** [comment]
### Fixed!
https://github.com/WieszakWare/Hackord/releases/tag/v2.0.4
